### ISSUE TITLE
[Bug]: upload vs. verify checks

### ISSUE THREAD

**Issue by ohaddahan** [metaplex-foundation/sugar#339]
### Issue description

1. Create a assets and collection.json
2. Mismatch `symbol`.
3. `verify` will pass.
4. `upload` will catch the different `symbol` in the `collection` vs. the assets.

### Priority this issue should have

Low (slightly annoying)

**Comment by samuelvanderwaal** [comment]
> ### Issue description
> 1. Create a assets and collection.json
> 2. Mismatch `symbol`.
> 3. `verify` will pass.
> 4. `upload` will catch the different `symbol` in the `collection` vs. the assets.
> 
> ### Relevant log output
> _No response_
> 
> ### Priority this issue should have
> Low (slightly annoying)

Do you mean that the `validate` command doesn't catch the difference in symbols?

**Comment by ohaddahan** [comment]
Maybe I mixed up the commands, but basically yeah.

From what I briefly see in the code, only on `upload` the `collection` content is read and compared vs. the `assets`.

**Comment by samuelvanderwaal** [comment]
After looking into this I believe this is actually the intended behavior: `validate` is designed to be independent of the config file and can be run on any assets directory without require a config file passed in as well. It validates the metadata format of the assets. Checking that the symbol matches the config file seems appropriate for `upload` because at the point it already requires that a config file exist.

I'm open to counter opinions on if this should work differently, but I think it's not a bug in the sense that this is the actually intended behavior.

**Comment by samuelvanderwaal** [comment]
@ohaddahan does that make sense?

**Comment by ohaddahan** [comment]
As I see it, if I'm running validations on the `assets` and `collection.json` is there, why not do it already.
But it's definitely not some big issue from my perspective, just noticed it and wanted to give a heads up.
