### ISSUE TITLE
[Bug]: I get this; Error running command (re-run needed): DataTypeMismatch. When I run the sugar deploy command

### ISSUE THREAD

**Issue by MaivaSoftwares** [metaplex-foundation/sugar#486]
### Issue description

I get this; Error running command (re-run needed): DataTypeMismatch. When I run the sugar deploy command

5/5 asset pair(s) uploaded.

>>> sugar deploy

[1/3] Creating collection NFT for candy machine

Collection mint already deployed.

[2/3] Creating candy machine

🛑 Error running command (re-run needed): DataTypeMismatch

Please help

### Relevant log output

```shell
🛑 Error running command (re-run needed): DataTypeMismatch
```

### Priority this issue should have

Medium (should be fixed soon)

**Comment by irzinfante** [comment]
I've encountered the same issue.

Two weeks ago I could deploy a NFT collection in **devnet** with Sugar v1.2.2, for Candy Machine V2, without running into this problem. But from about a week ago onwards, even if I can upload the files with `sugar upload` correctly, it will fail the deployment with `sugar deploy` with the error
![DataTypeMismatch](https://github.com/user-attachments/assets/72b54020-3231-4389-8a93-1e2d7ac98432)

I've tryed to uninstall sugar and reinstalling, as suggested here https://solana.stackexchange.com/questions/16439/candy-machine-error-running-command-datatypemismatch, but it didn't work.

I've also tryend deploying with Sugar v2, for Candy Machine V3, and even if it deploys the Candy Machine, the metadata doesn't seem to be uploaded in Arweave. I this last case I don't know if it is a problem due to Arweave, or if it may have to do with a bad configuration of the project, as it was meant to be deployed with Sugar v1.

Any help? In either case, Sugar v1 or v2, is there anything wrong with Arweave maybe?

**Comment by MaivaSoftwares** [comment]
You should locate were sugar is installed and uninstall it or delete it.
After that, go to environment variables and delete the path of sugar.

Then reinstall sugar and start your project in a new folder. This should
work

**Comment by MarkSackerberg** [comment]
Reinstalling / updating is the solution, correct.

@irzinfante the official arweave gateway is delayed currently. The data should be up some days later unfortunately.
Using the irys gateway by changing the beginning of the url from https://arweave.net/ to https://gateway.irys.xyz/ should work.

If you want to change your cache file for this open it, edit the URLs, set  `"onChain": true` to  `"onChain": false` for all of them and then run `sugar deploy` again

**Comment by JavierSanzSaez** [comment]
Hi, I'm facing the same issue. I did everything you all mentioned (reinstalling sugar after deleting the path/env variables, as well as changing the cache file urls from arweave to irys with `"onChain": false`) but still after running `sugar deploy` the same issue happens. This also is happening trying to create a candy machine from scratch (using `sugar launch`).

Is there anything in the sugar code that tries to directly read from the arweave url and not read from the cache file? Because I can read the metadata from Irys but still the same issue happens with `sugar verify`.
